python_sources = [
  '__init__.py',
]

py.install_sources(
  python_sources,
  subdir: 'fluidsim'
)

# TODO: add code to build the extensions
# see https://github.com/dnicolodi/python-siphash24/blob/master/meson.build
# of course, the Cython files have to be creates by something like
# `spy build --output-kind cython --no-compile ...`
