# mypy: ignore-errors
"""
Heap-allocated classes: the same tests for three implementations of `Point`.

    pytest examples/exp_record -m record     # point_record.spy: metaclass Record
    pytest examples/exp_record -m by-hand    # point_by_hand.spy: code generated by Record
    pytest examples/exp_record -m simple     # point_simple.spy: simplified, runs

The module name is the only thing that changes between the three: each test imports
`Point` from it. See README.md.
"""

from pathlib import Path

import pytest

from spy.tests.support import CompilerTest

HERE = Path(__file__).parent
METACLASSES = HERE.parent.parent / "stdlib" / "metaclasses"

# "by-hand" is not a valid Python identifier, hence the getattr
IMPLEMENTATIONS = [
    pytest.param(
        "point_record",
        marks=[
            pytest.mark.record,
            pytest.mark.xfail(reason="metaclasses written in SPy not supported yet"),
        ],
    ),
    pytest.param("point_by_hand", marks=getattr(pytest.mark, "by-hand")),
    pytest.param("point_simple", marks=pytest.mark.simple),
]


class TestPoint(CompilerTest):
    @pytest.fixture(params=IMPLEMENTATIONS)
    def module_name(self, request):
        return request.param

    @pytest.fixture(autouse=True)
    def add_to_path(self, init):
        # make `import point_record` and `import record` work (modules are flat:
        # there are no packages yet, so stdlib/metaclasses is a directory of the path)
        self.vm.path.append(str(HERE))
        self.vm.path.append(str(METACLASSES))

    def test_construct_and_method(self, module_name):
        src = f"""
        from {module_name} import Point

        def foo() -> i32:
            p = Point(3, 4)
            return p.norm2()
        """
        mod = self.compile(src)
        assert mod.foo() == 25

    def test_getattr_setattr(self, module_name):
        src = f"""
        from {module_name} import Point

        def foo() -> i32:
            p = Point(3, 4)
            p.x = 10
            return p.x * 100 + p.y
        """
        mod = self.compile(src)
        assert mod.foo() == 1004

    def test_aliasing(self, module_name):
        # the whole point of heap classes: `q = p` does NOT copy the data
        src = f"""
        from {module_name} import Point

        def foo() -> i32:
            p = Point(1, 2)
            q = p
            q.y = 99
            return p.y
        """
        mod = self.compile(src)
        assert mod.foo() == 99

    def test_mutation_through_call(self, module_name):
        src = f"""
        from {module_name} import Point

        def move_right(p: Point) -> None:
            p.x = p.x + 1

        def foo() -> i32:
            p = Point(1, 2)
            move_right(p)
            move_right(p)
            return p.x
        """
        mod = self.compile(src)
        assert mod.foo() == 3

    def test_independent_instances(self, module_name):
        src = f"""
        from {module_name} import Point

        def foo() -> i32:
            p = Point(1, 2)
            q = Point(1, 2)
            q.x = 50
            return p.x
        """
        mod = self.compile(src)
        assert mod.foo() == 1

    def test_identity(self, request, module_name):
        request.applymarker(
            pytest.mark.xfail(reason="`is` on value types needs an __is__ hook")
        )
        src = f"""
        from {module_name} import Point

        def same() -> bool:
            p = Point(1, 2)
            q = p
            return p is q

        def different() -> bool:
            return Point(1, 2) is Point(1, 2)
        """
        mod = self.compile(src)
        assert mod.same() is True
        assert mod.different() is False

    def test_init_from_fields(self, module_name):
        src = f"""
        from {module_name} import Point

        def foo() -> i32:
            p = Point(3, 4)
            return p.x * 10 + p.y
        """
        mod = self.compile(src)
        assert mod.foo() == 34

    def test_eq(self, module_name):
        # equality of the fields, not identity
        src = f"""
        from {module_name} import Point

        def foo() -> bool:
            return Point(1, 2) == Point(1, 2) and Point(1, 2) != Point(1, 3)
        """
        mod = self.compile(src)
        assert mod.foo() is True

    def test_repr(self, module_name):
        src = f"""
        from {module_name} import Point

        def foo() -> str:
            return repr(Point(1, 2))
        """
        mod = self.compile(src)
        assert mod.foo() == "Point(x=1, y=2)"
